language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - DJANGO_VERSION=Django==1.8
  - DJANGO_VERSION=Django==1.9

# command to install dependencies
install:
  - pip install celery>=2.5.2
  - pip install $DJANGO_VERSION

# command to run tests

script:
  - python runtests.py

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO_VERSION=Django==1.9
