language: python

python:
  - "2.7"
  - "3.3"

env:
  - DJANGO_VERSION=Django==1.4.2
  - DJANGO_VERSION=Django==1.4.3
  - DJANGO_VERSION=Django==1.4.4
  - DJANGO_VERSION=Django==1.4.5
  - DJANGO_VERSION=Django==1.5
  - DJANGO_VERSION=Django==1.5.1

# command to install dependencies
install:
  - pip install --use-mirrors $DJANGO_VERSION

# command to run tests

script:
  - python runtests.py

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO_VERSION=Django==1.4.2
    - python: "3.3"
      env: DJANGO_VERSION=Django==1.4.3
    - python: "3.3"
      env: DJANGO_VERSION=Django==1.4.4
    - python: "3.3"
      env: DJANGO_VERSION=Django==1.4.5
