language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

env:
  - DJANGO_VERSION=Django==1.8

# command to install dependencies
install:
  - pip install celery>=2.5.
  - pip install -r requirements.txt
  - pip install $DJANGO_VERSION

# command to run tests

script:
  - py.test mailqueue -x
