language: python

python:
  - "2.7"
  - "3.4"

env:
  - DJANGO_VERSION=Django==1.8
  - DJANGO_VERSION=Django==1.9
  - DJANGO_VERSION=Django==1.10
  - DJANGO_VERSION=Django==1.11

# command to install dependencies
install:
  - pip install celery>=3.1.23
  - pip install -r requirements.txt
  - pip install $DJANGO_VERSION

# command to run tests

script:
  - py.test mailqueue -x
